name: Автодеплой на EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Устанавливаем зависимости и билдим
        run: |
          npm ci
          npm run build

      - name: Синхронизируем файлы на сервер через rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz --delete --exclude .git --exclude node_modules
          path: .
          remote_host: ${{ vars.EC2_HOST }}
          remote_user: ${{ vars.EC2_USER }}
          remote_key: ${{ secrets.EC2_SSH_KEY }}
          remote_port: 22
          remote_path: ~/traffy-docs/

      - name: Деплой и рестарт на сервере
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v22.15.0/bin
            
            cd ~/traffy-docs/
      
            npm ci
      
            pm2 restart traffy-docs || \
            pm2 start npm --name traffy-docs -- run serve
